-- =============================================================================
-- 05_create_semantic_view.sql
-- Creates the Semantic View used by both agents (baseline is locked to it).
-- =============================================================================

USE SCHEMA DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION;

create or replace semantic view SAP_BASELINE_SV
	tables (
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.LFA1 primary key (LIFNR) comment='Vendor master data',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.MARA primary key (MATNR) comment='Material master data',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.EKPO primary key (EBELN,EBELP) comment='Purchasing document items',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.LIKP primary key (TKNUM) comment='Shipment data',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.T001W primary key (WERKS) comment='Plant data',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.T320 primary key (LGORT) comment='Storage location data',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.STPO primary key (STLNR,IDNRK) comment='BOM items',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.LFB1 primary key (LIFNR,VKONT) comment='Vendor contract data',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.QALS primary key (PRUEFLOS) comment='Inspection lot data',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.LFA2 primary key (TDLNR) comment='Forwarding agent data',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.BSEG primary key (BELNR,BUZEI) comment='Accounting document line items',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.COEP comment='Cost element line items',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.VBAP primary key (VBELN,POSNR) comment='Sales document items',
		DB_ONTOLOGY_CONTROL_PLANE.SAP_PRODUCTION.KONV comment='Pricing condition records'
	)
	relationships (
		EKPO_TO_LFA1 as EKPO(LIFNR) references LFA1(LIFNR),
		EKPO_TO_MARA as EKPO(MATNR) references MARA(MATNR),
		EKPO_TO_T001W as EKPO(WERKS) references T001W(WERKS),
		LIKP_TO_LFA2 as LIKP(TDLNR) references LFA2(TDLNR),
		LIKP_TO_T001W as LIKP(WERKS_DST) references T001W(WERKS),
		LIKP_TO_T320 as LIKP(LGORT_SRC) references T320(LGORT),
		T320_TO_T001W as T320(WERKS) references T001W(WERKS),
		LFB1_TO_LFA1 as LFB1(LIFNR) references LFA1(LIFNR),
		QALS_TO_MARA as QALS(MATNR) references MARA(MATNR),
		BSEG_TO_EKPO as BSEG(EBELN) references EKPO(EBELN),
		BSEG_TO_LFA1 as BSEG(LIFNR) references LFA1(LIFNR),
		VBAP_TO_MARA as VBAP(MATNR) references MARA(MATNR)
	)
	facts (
		MARA.STPRS as STPRS comment='Standard price',
		EKPO.MENGE as MENGE comment='Purchase order quantity',
		EKPO.NETWR as NETWR comment='Net order value',
		LIKP.MENGE as MENGE comment='Delivery quantity',
		LIKP.FRTCO as FRTCO comment='Freight cost',
		T320.LKAPA as LKAPA comment='Storage location capacity',
		STPO.MENGE as MENGE comment='Component quantity',
		STPO.STUFE as STUFE comment='BOM level',
		LFB1.JWERT as JWERT comment='Annual contract value',
		QALS.QAESSION as QAESSION comment='Defect rate',
		LFA2.LZEIT as LZEIT comment='Transit time',
		LFA2.OTRAT as OTRAT comment='On-time delivery rate',
		BSEG.DMBTR as DMBTR comment='Amount in local currency',
		COEP.WRTBTR as WRTBTR comment='Value in reporting currency',
		VBAP.KWMENG as KWMENG comment='Order quantity',
		VBAP.NETWR as NETWR comment='Net value',
		KONV.KBETR as KBETR comment='Rate',
		KONV.KWERT as KWERT comment='Condition value'
	)
	dimensions (
		LFA1.LIFNR as LIFNR comment='Vendor number',
		LFA1.NAME1 as NAME1 comment='Vendor name',
		LFA1.ORT01 as ORT01 comment='City',
		LFA1.LAND1 as LAND1 comment='Country code',
		LFA1.KTOKK as KTOKK comment='Account group',
		LFA1.ZTERM as ZTERM comment='Payment terms key',
		MARA.MATNR as MATNR comment='Material number',
		MARA.MAKTX as MAKTX comment='Material description',
		MARA.MATKL as MATKL comment='Material group',
		EKPO.EBELN as EBELN comment='Purchasing document number',
		EKPO.EBELP as EBELP comment='Item number',
		EKPO.LIFNR as LIFNR comment='Vendor number',
		EKPO.MATNR as MATNR comment='Material number',
		EKPO.WERKS as WERKS comment='Plant',
		EKPO.STATU as STATU comment='Status',
		EKPO.BEDAT as BEDAT comment='Purchasing document date',
		LIKP.TKNUM as TKNUM comment='Shipment number',
		LIKP.TDLNR as TDLNR comment='Forwarding agent',
		LIKP.LGORT_SRC as LGORT_SRC comment='Source storage location',
		LIKP.WERKS_DST as WERKS_DST comment='Destination plant',
		LIKP.MATNR as MATNR comment='Material number',
		LIKP.STATU as STATU comment='Delivery status',
		LIKP.LFDAT as LFDAT comment='Delivery date',
		LIKP.WADAT as WADAT comment='Goods issue date',
		T001W.WERKS as WERKS comment='Plant',
		T001W.NAME1 as NAME1 comment='Name',
		T001W.REGIO as REGIO comment='Region',
		T320.LGORT as LGORT comment='Storage location',
		T320.LGOBE as LGOBE comment='Storage location description',
		T320.WERKS as WERKS comment='Plant',
		STPO.STLNR as STLNR comment='Bill of material',
		STPO.IDNRK as IDNRK comment='BOM component',
		LFB1.LIFNR as LIFNR comment='Vendor number',
		LFB1.VKONT as VKONT comment='Contract account',
		LFB1.VTART as VTART comment='Contract type',
		LFB1.DTEND as DTEND comment='Validity end date',
		QALS.PRUEFLOS as PRUEFLOS comment='Inspection lot',
		QALS.MATNR as MATNR comment='Material number',
		QALS.VCODE as VCODE comment='Usage decision code',
		LFA2.TDLNR as TDLNR comment='Forwarding agent',
		LFA2.NAME1 as NAME1 comment='Name',
		LFA2.VSART as VSART comment='Shipping type',
		BSEG.BELNR as BELNR comment='Document number',
		BSEG.BUZEI as BUZEI comment='Line item',
		BSEG.EBELN as EBELN comment='Purchasing document number',
		BSEG.LIFNR as LIFNR comment='Vendor number',
		BSEG.HKONT as HKONT comment='GL account',
		BSEG.BSCHL as BSCHL comment='Posting key',
		BSEG.GJAHR as GJAHR comment='Fiscal year',
		BSEG.MONAT as MONAT comment='Fiscal period',
		BSEG.BUDAT as BUDAT comment='Posting date',
		COEP.OBJNR as OBJNR comment='Cost object number',
		COEP.KSTAR as KSTAR comment='Cost element',
		COEP.GJAHR as GJAHR comment='Fiscal year',
		COEP.PERIO as PERIO comment='Period',
		COEP.MATNR as MATNR comment='Material number',
		VBAP.VBELN as VBELN comment='Sales document',
		VBAP.POSNR as POSNR comment='Item number',
		VBAP.MATNR as MATNR comment='Material number',
		VBAP.KUNNR as KUNNR comment='Customer number',
		VBAP.VKORG as VKORG comment='Sales organization',
		VBAP.ERDAT as ERDAT comment='Created on date',
		KONV.KNUMV as KNUMV comment='Condition number',
		KONV.KPOSN as KPOSN comment='Condition item',
		KONV.KSCHL as KSCHL comment='Condition type',
		KONV.MATNR as MATNR comment='Material number',
		KONV.KUNNR as KUNNR comment='Customer number'
	)
	comment='SAP production data covering procurement, logistics, finance, and sales';
